# Generated by Django 5.0.6 on 2024-05-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
